// Groq API Client

import { Env, GroqRequest, GroqResponse } from '../types';
import { Logger } from '../utils/logger';
import SYSTEM_PROMPT from '../../commentator-persona.md';

const logger = new Logger('GroqClient');

/**
 * Generate a comment using Groq API
 */
export async function generateComment(
  env: Env,
  redditPostContent: string,
  redditPermalink: string
): Promise<string> {
  logger.info('Generating comment with Groq');
  
  const apiUrl = 'https://api.groq.com/openai/v1/chat/completions';
  logger.info(`Using Groq model: ${env.GROQ_MODEL}`);
  
  const userPrompt = `以下のRedditの投稿について、上記のペルソナに従って日本語でコメントを生成してください。

${redditPostContent}

【重要】改行を含めた全合計文字数を、必ず240文字以内に収めてください。これを超えるとシステムエラーになります。`;

  const request: GroqRequest = {
    model: env.GROQ_MODEL,
    messages: [
      {
        role: 'system',
        content: SYSTEM_PROMPT,
      },
      {
        role: 'user',
        content: userPrompt,
      },
    ],
    temperature: 0.7,
    max_tokens: 500,
  };
  
  const response = await fetch(apiUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${env.GROQ_API_KEY}`,
    },
    body: JSON.stringify(request),
  });
  
  if (!response.ok) {
    const errorText = await response.text();
    logger.error('Groq API request failed', { status: response.status, error: errorText });
    throw new Error(`Groq API request failed: ${response.status}`);
  }
  
  const data: GroqResponse = await response.json();
  
  if (!data.choices || data.choices.length === 0) {
    logger.error('No choices in Groq response', data);
    throw new Error('No comment generated by Groq');
  }
  
  const generatedText = data.choices[0].message.content;
  logger.info('Successfully generated comment', { length: generatedText.length });
  
  return generatedText;
}
