// Gemini API Client

import { Env, GeminiRequest, GeminiResponse } from '../types';
import { Logger } from '../utils/logger';
import SYSTEM_PROMPT from '../../commentator-persona.md';

const logger = new Logger('GeminiClient');

/**
 * Generate a comment using Gemini API
 */
export async function generateComment(
  env: Env,
  redditPostContent: string,
  redditPermalink: string
): Promise<string> {
  logger.info('Generating comment with Gemini');
  
  // Build API URL with model from environment
  const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/${env.GEMINI_MODEL}:generateContent`;
  logger.info(`Using Gemini model: ${env.GEMINI_MODEL}`);
  
const userPrompt = `以下のRedditの投稿について、上記のペルソナに従って日本語でコメントを生成してください。

${redditPostContent}

【重要】改行を含めた全合計文字数を、必ず240文字以内に収めてください。これを超えるとシステムエラーになります。`;

  const request: GeminiRequest = {
    contents: [
      {
        role: 'user',
        parts: [{ text: userPrompt }],
      },
    ],
    systemInstruction: {
      parts: [{ text: SYSTEM_PROMPT }],
    },
  };
  
  const response = await fetch(`${apiUrl}?key=${env.GEMINI_API_KEY}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(request),
  });
  
  if (!response.ok) {
    const errorText = await response.text();
    logger.error('Gemini API request failed', { status: response.status, error: errorText });
    throw new Error(`Gemini API request failed: ${response.status}`);
  }
  
  const data: GeminiResponse = await response.json();
  
  if (!data.candidates || data.candidates.length === 0) {
    logger.error('No candidates in Gemini response', data);
    throw new Error('No comment generated by Gemini');
  }
  
  const generatedText = data.candidates[0].content.parts[0].text;
  logger.info('Successfully generated comment', { length: generatedText.length });
  
  return generatedText;
}
