// Cloudflare Workers AI Client

import { Env, CloudflareAIRequest, CloudflareAIResponse } from '../types';
import { Logger } from '../utils/logger';
import SYSTEM_PROMPT from '../../commentator-persona.md';

const logger = new Logger('CloudflareAIClient');

/**
 * Generate a comment using Cloudflare Workers AI
 */
export async function generateComment(
  env: Env,
  redditPostContent: string,
  redditPermalink: string
): Promise<string> {
  logger.info('Generating comment with Cloudflare Workers AI');
  
  if (!env.AI) {
    throw new Error('AI binding is not configured');
  }
  
  const model = env.CLOUDFLARE_AI_MODEL || '@cf/meta/llama-3.1-8b-instruct';
  logger.info(`Using Cloudflare AI model: ${model}`);
  
  const userPrompt = `以下のRedditの投稿について、上記のペルソナに従って日本語でコメントを生成してください。

${redditPostContent}

【重要】改行を含めた全合計文字数を、必ず240文字以内に収めてください。これを超えるとシステムエラーになります。`;

  const request: CloudflareAIRequest = {
    messages: [
      {
        role: 'system',
        content: SYSTEM_PROMPT,
      },
      {
        role: 'user',
        content: userPrompt,
      },
    ],
  };
  
  try {
    const response = await env.AI.run(model as any, request) as CloudflareAIResponse;
    
    if (!response || !response.response) {
      logger.error('No response from Cloudflare AI', response);
      throw new Error('No comment generated by Cloudflare AI');
    }
    
    const generatedText = response.response;
    logger.info('Successfully generated comment', { length: generatedText.length });
    
    return generatedText;
  } catch (error) {
    logger.error('Cloudflare AI request failed', error);
    throw error;
  }
}
